RecipeViewerEvents.removeEntries('item', event => {
  event.remove('minecraft:copper_ingot')
  event.remove('minecraft:iron_ingot')
  event.remove('minecraft:gold_ingot')
  event.remove('minecraft:netherite_helmet')
  event.remove('minecraft:netherite_chestplate')
  event.remove('create:crushed_raw_silver')
  event.remove('create:crushed_raw_tin')
  event.remove('create:crushed_raw_nickel')
  event.remove('create:zinc_ingot')
  event.remove('create:brass_ingot')
  event.remove('create:copper_sheet')
  event.remove('create:brass_sheet')
  event.remove('create:iron_sheet')
  event.remove('create:golden_sheet')
  event.remove('create:empty_blaze_burner')
  event.remove('create:blaze_cake')
  event.remove('tfc:food/dried_kelp')
  event.remove('kubejs:incomplete_brass_mechanisms')
  event.remove('kubejs:incomplete_circular_saw')
})

RecipeViewerEvents.removeEntries('fluid', event => {
  event.remove('kubejs:potion_beer')
  event.remove('kubejs:potion_cider')
  event.remove('kubejs:potion_rum')
  event.remove('kubejs:potion_sake')
  event.remove('kubejs:potion_vodka')
  event.remove('kubejs:potion_whiskey')
  event.remove('kubejs:potion_corn_whiskey')
  event.remove('kubejs:potion_rye_whiskey')
  event.remove('kubejs:potion_strong_beer')
  event.remove('kubejs:potion_strong_cider')
  event.remove('kubejs:potion_strong_rum')
  event.remove('kubejs:potion_strong_sake')
  event.remove('kubejs:potion_strong_vodka')
  event.remove('kubejs:potion_strong_whiskey')
  event.remove('kubejs:potion_strong_corn_whiskey')
  event.remove('kubejs:potion_strong_rye_whiskey')
})

RecipeViewerEvents.removeCategories(event => {
  event.remove('minecraft:anvil')
  event.remove('minecraft:brewing')
  event.remove('minecraft:blasting')
  event.remove('minecraft:campfire')
  event.remove('minecraft:compostable')
  event.remove('minecraft:fuel')
  event.remove('minecraft:furnace')
  event.remove('minecraft:smithing')
  event.remove('minecraft:smoking')
  event.remove('minecraft:stonecutting')
  event.remove('create:fan_haunting')
})
